export const carts = [
	{
		id: 1,
		img: '/minidivan.png',
		imgAlt: 'minidivan_png',
		title: 'Кускен Navy Blue',
		color: 'Темно-синий',
		price: '16 990₽',
		count: 1,
		size: '218 СМ × 95 СМ × 90 СМ',
	},
	{
		id: 2,
		img: '/minidivan.png',
		imgAlt: 'minidivan_png',
		title: 'Кускен Navy Blue',
		color: 'Темно-синий',
		price: '16 990₽',
		count: 1,
		size: '218 СМ × 95 СМ × 90 СМ',
	},
	{
		id: 3,
		img: '/minidivan.png',
		imgAlt: 'minidivan_png',
		title: 'Кускен Navy Blue',
		color: 'Темно-синий',
		price: '16 990₽',
		count: 1,
		size: '218 СМ × 95 СМ × 90 СМ',
	},
	{
		id: 4,
		img: '/minidivan.png',
		imgAlt: 'minidivan_png',
		title: 'Кускен Navy Blue',
		color: 'Темно-синий',
		price: '16 990₽',
		count: 1,
		size: '218 СМ × 95 СМ × 90 СМ',
	},
]